version: '3'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    depends_on:
      - database
  database:
    image: nouchka/sqlite3
    volumes:
      - ./data:/usr/src/app/data

